### PR TITLE
adding gcc-7 solved the eta problem in my vm

### PR DESCRIPTION
**Pull request by nevrome**

### CODE REVIEW

**Comment by nevrome** [comment]
Wohoo! It works.

**Comment by kforner** [comment]
Cool !

**Comment by kforner** [comment]
Do you know why your code requires gcc7 ? Instead of requiring gcc7, it could be better to rewrite the needed part, it would increase the portability of the package.

**Comment by nevrome** [comment]
Ok - I did what i should have done at the beginning: I compiled the eta code with g++-4.9. Turns out <ctime> and <time.h> is not exactly the same. Now it should work also with the older compiler versions.

Do you have an idea why testthat causes problems in the travis build? That's not related to the compiler changes, or?

**Comment by kforner** [comment]
On Mon, Nov 13, 2017 at 2:14 PM, Clemens Schmid <notifications@github.com>
wrote:

> Ok - I did what i should have done at the beginning: I compiled the eta
> code with g++-4.9. Turns out and <time.h> is not exactly the same. Now it
> should work also with the older compiler versions.
>
> Do you have an idea why testthat causes problems in the travis build?
> That's not related to the compiler changes, or?
>

I think it is not testthat, it's once again the compilation of
RcppProgressETA that fails:
https://travis-ci.org/kforner/rcpp_progress/builds/301386887

0.94schecking tests ... ERROR

Running ‘testthat.R’ [37s/30s]

Running the tests in ‘tests/testthat.R’ failed.

Last 13 lines of output:

7: force(code)

8: install_min(pkg, install_dir, components = "libs", args = if
(needs_clean(pkg)) "--preclean",

quiet = quiet)

9: RCMD("INSTALL", c(shQuote(pkg$path), paste("--library=", shQuote(dest),
sep = ""),

no_args, "--no-multiarch", "--no-test-load", args), quiet = quiet)

10: R(paste("CMD", cmd, options), path = path, env_vars = env_vars, ...)

11: fun(r, args = args, env_vars = env_vars, path = path, ...)

12: stop("Command failed (", status, ")", call. = FALSE)

testthat results
================================================================

OK: 1 SKIPPED: 0 FAILED: 1

1. Error: eta_progress_bar (@test-pkg_examples.R#26)

Error: testthat unit tests failed

Execution halted

**Comment by kforner** [comment]
yes but afterwards I removed the make tests in travis config file.

**Comment by kforner** [comment]
Sorry, I'm confused there're too much changes. 
Could you please make a PR with only the gcc6-related changes, i.e. the ctime/time stuff ?

**Pull request closed without merging**
